//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//
//     对此文件的更改可能导致不正确的行为，并在以下条件下丢失:
//     代码重新生成。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elecinvoice
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Elecinvoice.ServiceSoap")]
    public interface ServiceSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BusinessElectInvoice", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string BusinessElectInvoice(string jsonValue);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BusinessElectInvoice", ReplyAction="*")]
        System.Threading.Tasks.Task<string> BusinessElectInvoiceAsync(string jsonValue);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BusinessElectInvoice_SECRET", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string BusinessElectInvoice_SECRET(string xmlstr, string user_id, string signature);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BusinessElectInvoice_SECRET", ReplyAction="*")]
        System.Threading.Tasks.Task<string> BusinessElectInvoice_SECRETAsync(string xmlstr, string user_id, string signature);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CREATEQD", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CREATEQD(string HOS_ID, string request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CREATEQD", ReplyAction="*")]
        System.Threading.Tasks.Task<string> CREATEQDAsync(string HOS_ID, string request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BusinessElectInvoiceForPYS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string BusinessElectInvoiceForPYS(string jsonValue);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BusinessElectInvoiceForPYS", ReplyAction="*")]
        System.Threading.Tasks.Task<string> BusinessElectInvoiceForPYSAsync(string jsonValue);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CALLSLB", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CALLSLB(string slbURL, string SubBusID, string BusData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CALLSLB", ReplyAction="*")]
        System.Threading.Tasks.Task<string> CALLSLBAsync(string slbURL, string SubBusID, string BusData);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface ServiceSoapChannel : Elecinvoice.ServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<Elecinvoice.ServiceSoap>, Elecinvoice.ServiceSoap
    {
        
        /// <summary>
        /// 实现此分部方法，配置服务终结点。
        /// </summary>
        /// <param name="serviceEndpoint">要配置的终结点</param>
        /// <param name="clientCredentials">客户端凭据</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(ServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), ServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public string BusinessElectInvoice(string jsonValue)
        {
            return base.Channel.BusinessElectInvoice(jsonValue);
        }
        
        public System.Threading.Tasks.Task<string> BusinessElectInvoiceAsync(string jsonValue)
        {
            return base.Channel.BusinessElectInvoiceAsync(jsonValue);
        }
        
        public string BusinessElectInvoice_SECRET(string xmlstr, string user_id, string signature)
        {
            return base.Channel.BusinessElectInvoice_SECRET(xmlstr, user_id, signature);
        }
        
        public System.Threading.Tasks.Task<string> BusinessElectInvoice_SECRETAsync(string xmlstr, string user_id, string signature)
        {
            return base.Channel.BusinessElectInvoice_SECRETAsync(xmlstr, user_id, signature);
        }
        
        public string CREATEQD(string HOS_ID, string request)
        {
            return base.Channel.CREATEQD(HOS_ID, request);
        }
        
        public System.Threading.Tasks.Task<string> CREATEQDAsync(string HOS_ID, string request)
        {
            return base.Channel.CREATEQDAsync(HOS_ID, request);
        }
        
        public string BusinessElectInvoiceForPYS(string jsonValue)
        {
            return base.Channel.BusinessElectInvoiceForPYS(jsonValue);
        }
        
        public System.Threading.Tasks.Task<string> BusinessElectInvoiceForPYSAsync(string jsonValue)
        {
            return base.Channel.BusinessElectInvoiceForPYSAsync(jsonValue);
        }
        
        public string CALLSLB(string slbURL, string SubBusID, string BusData)
        {
            return base.Channel.CALLSLB(slbURL, SubBusID, BusData);
        }
        
        public System.Threading.Tasks.Task<string> CALLSLBAsync(string slbURL, string SubBusID, string BusData)
        {
            return base.Channel.CALLSLBAsync(slbURL, SubBusID, BusData);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.ServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("找不到名称为“{0}”的终结点。", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://192.168.3.46:8088/Service.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.ServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://192.168.3.46:8088/Service.asmx");
            }
            throw new System.InvalidOperationException(string.Format("找不到名称为“{0}”的终结点。", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            ServiceSoap,
            
            ServiceSoap12,
        }
    }
}
